### ISSUE TITLE
Red Buttons Of Death

### ISSUE THREAD

**Issue by Exhillious** [AlexALX/wiremod_e2_os#1]
So, whenever I dupe the creation, the GPU and the HDD controllers on all creations turn red. And whenever I attempt to use the E2 part of the creation (Chipset, etc.) it doesn't allow me to load. I have tried this on different computers, and still doesn't work.

**Comment by AlexALX** [comment]
Can you please open console and copy any errors from wiremod/e2 what might appear when you trying to load chip? Anyway if its tick quota or something like this - then your server or wiremod configuration is not meet minimum rates what this e2 require. Also its possible that you don't have needed e2 extensions enabled like http or whatever.

**Comment by AlexALX** [comment]
I think this issue is due to lack of some e2 extensions, upcoming version 1.2 will able to work without any e2 extension, so this should be fixed after i release new version.
