### ISSUE TITLE
CD drive doesn't work//Дисковод не работает

### ISSUE THREAD

**Issue by qSNARKp** [AlexALX/wiremod_e2_os#10]
При попытке запустить установку системы появляется такая ошибка 
![Screenshot_280](https://user-images.githubusercontent.com/83895370/117560353-aba6a780-b0bf-11eb-8fdb-2bb7a4fc22aa.png)
 и чип на дисководе становится красный(script error). Как я понял что ему не хватает файла самой ОС после уже взял ее с гитхаба и сразу количество операций в чипе увеличелось, но дисковод перестал определяться в системе

**Comment by AlexALX** [comment]
ваирмод последний? При вставке дупликата ошибок нет? Словно какогото обьекта не хватает.

**Comment by qSNARKp** [comment]
Последняя версия ваирмода. При вставки ошибок нету.

**Comment by qSNARKp** [comment]
https://www.youtube.com/watch?v=eulCAhlRkDQ вот что происходит. Раньше он жаловался на отсутствие файла _main_
но после его добавление ничего особо не изменилось

**Comment by AlexALX** [comment]
проверь на любом публичном сервере с ваир модом - если будет пахать, то проблема на твоей стороне, возможно конфликт с каким либо аддоном. ошибка вообще ваира, даже не пишет в чём причина (код корректен), чтото забаговалось у тебя возможно.

**Comment by qSNARKp** [comment]
Похоже проблема была в версии wiremod ибо спустя время все заработало как нужно
