### ISSUE TITLE
CD Drive Script error english

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [AlexALX/wiremod_e2_os#11]
when i try to boot to cd drive it doesn't work due to it trying to get a null entity. I am playing in singleplayer. I am trying to install the OS. any ideas?

**Comment by AlexALX** [comment]
Just wrote on workshop page:

> @everyone - new gmod update did broke few wiremod functions what uses this mod. currently workshop version of wiremod does NOT included fix, you must use GIT version of wiremod.

**Comment by IAmTheNerdNextDoor** [comment]
Thanks!

**Comment by AlexALX** [comment]
It should be fixed long time ago already, so closing this.
