### ISSUE TITLE
Issue Setting Up

### ISSUE THREAD

**Issue by LanaMantegazza** [AlexALX/wiremod_e2_os#3]
sv: Expression 2 (HDD Controller): Function wm1_getsize(table FS,number C) executed and didn't return a value - expecting a value of type number
Any idea why?
I Get this issue whenever i try to set up the ALX OS

**Comment by AlexALX** [comment]
Its due to latest changes in wiremod, i'm working on major update for this project so this will be fixed, as for now you may just wait, i can release hot fix but better to wait for full update.
