### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Andrew-Eathan** [AlexALX/wiremod_e2_os#4]
how does the EGP screen get the screen data from the GPU? what does the GPU send to the EGP screen exactly?

**Comment by AlexALX** [comment]
GPU works with EGP directly via wirelink (and EGP e2 functions), so in GPU there is code for render everything on EGP, while CPU only have boot loader and do some calculations. Its pretty cosmetic division as its still E2 only.

**Comment by Andrew-Eathan** [comment]
oops, i meant how does the GPU connect to the EGP screen with just a plug and socket connection? how does it send the data to the EGP with datasignal wirelinks?

**Comment by AlexALX** [comment]
Ah, it does not actually use plug/socket to work via EGP, everything what those sockets do - is transmitting entity ID and wirelink via datasignal.

**Comment by Andrew-Eathan** [comment]
oh, ok. thanks!
