### ISSUE TITLE
spawn error

### ISSUE THREAD

**Issue by Jphgamer14** [AlexALX/wiremod_e2_os#5]
when i try to spawn swome of the things i get lua/advdupe2/sv_clipboard:742: bad argument #1 to 'isvalidmodel' (string expected, got nil)

**Comment by AlexALX** [comment]
I remember this error was in old versions of advdupe2, make sure you using latest one from workshop or github - https://github.com/wiremod/advdupe2 Feel free to open issue again if you still have this error after recheck
