### ISSUE TITLE
Del not recognized

### ISSUE THREAD

**Issue by MrLava13** [AlexALX/wiremod_e2_os#6]
Hello there, whenever I press del on boot to configure the BIOs the screen sort of just resets. I have tried countless times with multiple keyboards.
Best regards,
Scotty

**Comment by AlexALX** [comment]
maybe you have something wrong with gmod keybinds? never had any issues with del yet.

**Comment by danktememes** [comment]
I have the same issue is there a way to fix it??.

**Comment by MrLava13** [comment]
I had a problem with my computer, so I had to reinstall Garry's Mod, and I got rid of multiple addons. It can be an addon confliction error as it is working for me.

**Comment by danktememes** [comment]
ok thank you
