### ISSUE TITLE
HTTP E2 Extension & Internet dish don't work // Не работает интернет

### ISSUE THREAD

**Issue by w32u** [AlexALX/wiremod_e2_os#7]
When I'm trying to create an internet dish, it gives me this error (on pic) // Когда я создаю тарелку для работы интернета, то выскакивает данная ошибка (на картинке)
![20190722155313_1](https://user-images.githubusercontent.com/40323117/61634880-fd87fe80-ac9a-11e9-9722-cac64e6c071b.jpg)
Is there any way how to fix it? // Как исправить это недоразумение?

**Comment by AlexALX** [comment]
You need to enable e2 extension with command wire_expression2_extension_enable http (in console). If in singleplayer. If multiplayer - need to ask admin to enable this extension.

---

Нужно включить e2 расширение с помощью команды wire_expression2_extension_enable http. Если это в сингле конечно, а так просить админа на сервере включить.
