### ISSUE TITLE
Creating file problems

### ISSUE THREAD

**Issue by ghost** [AlexALX/wiremod_e2_os#8]
I just wanted to create a file by url but it doesn't work without E2 HTTP Extension, how do I fix it?

Here's error when I tried to put internet dish:
![error](https://user-images.githubusercontent.com/22994912/65425340-69f7b900-de16-11e9-85d9-d7ae6b7bed3f.png)

**Comment by AlexALX** [comment]
You should run this command in console:
wire_expression2_extension_enable http

If its multiplayer - then ask admin to enable it via this command.

**Comment by ghost** [comment]
Thank you so much it works now.
