### ISSUE TITLE
Motherboard Plugs don't work

### ISSUE THREAD

**Issue by Micka101** [AlexALX/wiremod_e2_os#9]
Ok so when I wanna place my motherboard the plugs don't attach and don't do anything.

**Comment by AlexALX** [comment]
Do you have latest wiremod and gmod?

**Comment by Micka101** [comment]
Yes I do.

**Comment by Micka101** [comment]
And every other parts places at the right places.

**Comment by Micka101** [comment]
I restarted gmod and now it works lmao
